# permissions for end users to edit custommodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simple-ollama-operator
    app.kubernetes.io/managed-by: kustomize
  name: custommodel-editor-role
rules:
- apiGroups:
  - ollama.ollama.startupnation
  resources:
  - custommodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ollama.ollama.startupnation
  resources:
  - custommodels/status
  verbs:
  - get
