---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ollama.ollama.startupnation
  resources:
  - models
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ollama.ollama.startupnation
  resources:
  - models/finalizers
  verbs:
  - update
- apiGroups:
  - ollama.ollama.startupnation
  resources:
  - models/status
  verbs:
  - get
  - patch
  - update
