apiVersion: ollama.ollama.startupnation/v1
kind: CustomModel
metadata:
  labels:
    app.kubernetes.io/name: simple-ollama-operator
    app.kubernetes.io/managed-by: kustomize
  name: mario-custommodel-sample
spec:
  modelName: mario-custommodel-sample:v1
  modelFile: "FROM llama3\nSYSTEM You are mario from Super Mario Bros."